insert into
    public.tourist_spots (
        id,
        name,
        description,
        spot_type,
        address,
        city,
        province,
        location,
        google_maps_place_id,
        contact_phone,
        contact_email,
        website,
        opening_time,
        closing_time,
        entry_fee,
        status,
        is_featured,
        average_rating,
        review_count,
        created_at,
        updated_at,
        created_by,
        updated_by,
        picture
    )
values
    -- 1 - active
    (
        uuid_generate_v4 (),
        'Basilica of Our Lady of Peñafrancia',
        'A major Roman Catholic church and pilgrimage site.',
        'religious',
        'Balatas Road',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1839 13.6189)'),
        'ChIJO8EuDcbnkzMRHEqpt-UG-Gs',
        '09171234567',
        'info@penafrancia.org',
        'https://penafrancia.net',
        '06:00',
        '20:00',
        0.00,
        'active',
        true,
        4.8,
        1200,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 2 - active
    (
        uuid_generate_v4 (),
        'Naga City Ecological Park',
        'A green space with trails, picnic areas, and environmental education.',
        'natural',
        'Pacol Road',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.2200 13.6412)'),
        null,
        null,
        null,
        null,
        '07:00',
        '18:00',
        20.00,
        'active',
        false,
        4.2,
        240,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 3 - pending
    (
        uuid_generate_v4 (),
        'Plaza Rizal',
        'A public square in the heart of Naga City dedicated to Dr. José Rizal.',
        'historical',
        'Peñafrancia Avenue',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1870 13.6260)'),
        null,
        null,
        null,
        null,
        '06:00',
        '21:00',
        0.00,
        'pending',
        false,
        4.0,
        80,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 4 - under_maintenance
    (
        uuid_generate_v4 (),
        'Panicuason Hot Spring Resort',
        'Natural hot spring resort with pools surrounded by lush forests.',
        'recreational',
        'Panicuason',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.2621 13.6621)'),
        null,
        '09180000001',
        null,
        null,
        '08:00',
        '22:00',
        150.00,
        'under_maintenance',
        true,
        4.5,
        350,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 5 - active
    (
        uuid_generate_v4 (),
        'Malabsay Falls',
        'A picturesque waterfall ideal for hiking and swimming.',
        'natural',
        'Mt. Isarog National Park',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.2750 13.6600)'),
        null,
        null,
        null,
        null,
        '07:00',
        '17:00',
        50.00,
        'active',
        true,
        4.7,
        420,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 6 - inactive
    (
        uuid_generate_v4 (),
        'Naga City Metropolitan Cathedral',
        'A baroque-style cathedral and seat of the Archdiocese of Caceres.',
        'religious',
        'Elias Angeles St.',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1867 13.6234)'),
        null,
        null,
        null,
        null,
        '05:30',
        '20:00',
        0.00,
        'inactive',
        false,
        4.6,
        580,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 7 - coming_soon
    (
        uuid_generate_v4 (),
        'Ateneo de Naga University Museum',
        'A museum showcasing regional history and culture.',
        'cultural',
        'Ateneo Avenue, Bagumbayan Sur',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1921 13.6223)'),
        null,
        null,
        null,
        null,
        '08:00',
        '17:00',
        30.00,
        'coming_soon',
        false,
        null,
        0,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 8 - active
    (
        uuid_generate_v4 (),
        'Mt. Isarog Trailhead',
        'Starting point for hikes up Mt. Isarog, popular with adventurers.',
        'natural',
        'Barangay Panicuason',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.2600 13.6700)'),
        null,
        null,
        null,
        null,
        '05:00',
        '17:00',
        100.00,
        'active',
        false,
        4.9,
        210,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 9 - pending
    (
        uuid_generate_v4 (),
        'Naga City Boardwalk',
        'A riverside boardwalk for strolling, biking, and relaxation.',
        'recreational',
        'Naga River, Dayangdang',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1944 13.6275)'),
        null,
        null,
        null,
        null,
        '06:00',
        '22:00',
        0.00,
        'pending',
        false,
        4.3,
        150,
        now (),
        now (),
        null,
        null,
        null
    ),
    -- 10 - active
    (
        uuid_generate_v4 (),
        'Jesse M. Robredo Museum',
        'Museum honoring the legacy of former DILG Secretary Jesse Robredo.',
        'cultural',
        'Panganiban Dr.',
        'Naga City',
        'Camarines Sur',
        ST_GeogFromText ('SRID=4326;POINT(123.1999 13.6272)'),
        null,
        null,
        null,
        null,
        '09:00',
        '17:00',
        0.00,
        'active',
        true,
        4.4,
        100,
        now (),
        now (),
        null,
        null,
        null
    );